### ISSUE TITLE
Search doesn't work with Cyrillic characters

### ISSUE THREAD

**Issue by MafiaInc** [bauerj/paperless_app#38] opened 2021-03-26 09:34 UTC
**Describe the bug**
By using the search bar on top, I can't find any document when searching with Cyrillic characters. This issue doesn't present when using the web application from the browser. Also it doesn't present if I search with Latin characters e.g. English words.

**To Reproduce**
1. Open Paperless app on Android
2. Make sure you have some documents written with language with Cyrillic words. 
3. Search for any of the words that you expect to find these documents.
4. You should see no documents found e.g. empty search results

**Expected behavior**
To list all the documents which match the word(s) in the search bar.

**Screenshots**
No screenshot as it's very clear. Let me know if screenshots or some debug information would be needed. With some basics how to extract it.

**Additional information**
*Paperless App Version*: 0.0.10 from F-Droid
*Do you use Paperless NG as a backend*: Yes

**Comment by bauerj** [comment] 2021-03-26 09:37
Thanks for reporting this. Are you searching for text in the document content or metadata like title or correspondent?

**Comment by MafiaInc** [comment] 2021-03-27 07:21
Acually I just found out that if I search for a tag it works. So I was searching for document content when I reported the issue.

**Comment by bauerj** [comment] 2021-04-06 08:31
Hey @MafiaInc,

sorry for my late response. I just looked into this and was unable to reproduce your issue:

![Screenshot_20210406_100730_eu bauerj paperless_app](https://user-images.githubusercontent.com/598790/113682022-f39e6d00-96c2-11eb-9213-7500222cfcdd.jpg)

This is what I did:

1. Changed the content of one of my documents to "Міжнаро́дная касмі́чная ста́нцыя, скарочана МКС (англ.: International Space Station, скароч. ISS) — пілатаваная арбітальная станцыя, якая выкарыстоўваецца як шматмэтавы касмічны даследчы комплекс. МКС — сумесны міжнародны праект, у якім удзельнічаюць 15 краін (у алфавітным парадку): Бельгія, Бразілія, Германія, Данія, Іспанія, Італія, Канада, Нідэрланды, Нарвегія, Расія, ЗША, Францыя, Швейцарыя, Швецыя, Японія.[12][13][14][кам. 1]."
2. Searched for "Міжнаро́дная" in Paperless App

So I'm not sure what causes the issue you are seeing. It doesn't seem to be an encoding issue. What Paperless version do you use? I'm on Paperless-ng 1.3.2.

**Comment by bauerj** [comment] 2021-04-21 12:52
Hey,

I'm closing this issue since we were unable to reproduce this and have not received further information. I hope this works for you now, otherwise please feel free to reopen the issue.

**Comment by MafiaInc** [comment] 2021-04-21 14:53
Hi, 
I am sorry I had some time off and didn't notice your previous comments. I will retest with latest version from F-Droid and will give more information. 
Thanks!

**Comment by bauerj** [comment] 2021-04-21 14:57
Thank you, I hope we will find out what exactly causes this!

**Comment by MafiaInc** [comment] 2021-04-21 16:48
I think I can't reproduce it now. I think I know what happened before. Now I have bigger database of documents and when I reported the issue there were only few. I don't remember the exact phrase Inwas using for back then. Now I tried with few more and found out that documets are found as expected. :) However I noticed that search is case sensitive, so most likely wast time I used only small letters for a phrase and the fact that I had only few documents I didn't notice it is case sensitive, which is something I could not expect.. :) Thanks for the attention, you may close the issue. 
Cheers

**Comment by bauerj** [comment] 2021-04-22 08:26
Okay, thanks for confirming!

**Closed by bauerj** 2021-04-22 08:26 UTC
Labels: bug, information-needed
