### ISSUE TITLE
Cannot login using 0.0.10

### ISSUE THREAD

**Issue by mvdkleijn** [bauerj/paperless_app#33] opened 2021-01-10 00:04 UTC
**Describe the bug**
Trying to log into a paperless-ng install results in Dio Error status 200. (see image)

**To Reproduce**
1. Configure http://url:8000/ in app
2. Add user and password

**Expected behavior**
Be logged into paperless.

**Screenshots**
![Screenshot_20210110-005140.jpg](https://user-images.githubusercontent.com/431452/104111182-6758f580-52df-11eb-8c0d-8ee6b461f7e9.jpg)

**Additional information**
*Paperless App Version*: 0.0.10
*Do you use Paperless NG as a backend*: Yes

Login tested using curl and browser, both work fine.

**Comment by qcasey** [comment] 2021-01-10 02:54
Poked around, and found this happening when there's a trailing slash in the server URL

`http://192.168.1.17:8000` works while `http://192.168.1.17:8000/` throws the above error.

I can help fix this upcoming week

**Comment by jonaswinkler** [comment] 2021-01-10 09:00
If I recall correctly, other api endpoints such as documents/ do need a trailing slash, so watch out for that.

**Comment by mvdkleijn** [comment] 2021-01-10 19:47
I tried it with and without the trailing slash but both give the same result.

Could this be caused by a slightly out of date paperless-ng install?

**Comment by jonaswinkler** [comment] 2021-01-10 19:52
After 0.9.5, nothing changed in regards to authentication.

**Comment by bauerj** [comment] 2021-01-11 11:01
Can you give us a URL to test? You can send it to me via email if you don't want to give it out publicly.

**Comment by mvdkleijn** [comment] 2021-01-11 12:22
@bauerj it's an install on an internal network so I'd prefer not to expose it unless there's no other way...

I use paperless through a vpn connection or on my local wifi.

After I get the initial error (even though the code is 200), I exit the app and re-open it... then I get the following error:

![Screenshot_20210111-131719.jpg](https://user-images.githubusercontent.com/431452/104181989-041ab080-5410-11eb-89e9-6ee996fede9a.jpg)

**Comment by bauerj** [comment] 2021-01-11 12:25
Sure, no problem.

This looks like the server returns a single integer (maybe 200?) instead of the expected JSON. Do you use a reverse proxy in front of your Paperless NG installation or do you connect directly to it?

**Comment by mvdkleijn** [comment] 2021-01-11 12:45
Apologies! I've found the problem. I was still running the 0.9.4 paperless-ng backend because it was a pain to upgrade since I'm running on arm (raspberry pi with Ubuntu) and Jonas did not have a pre-built arm Docker image.

However, I noticed that @jonaswinkler has a three day old multi arch image now, so I tried that. It resolves my problem and appears to work fine now.

Thanks! Closing.

**Comment by jonaswinkler** [comment] 2021-01-11 12:56
> However, I noticed that @jonaswinkler has a three day old multi arch image now, so I tried that. It resolves my problem and appears to work fine now.

See https://github.com/jonaswinkler/paperless-ng/issues/322.

**Comment by shtrom** [comment] 2021-06-03 12:50
Same issue here. Removing the trailing slash from the base URL magically worked.

**Comment by amihaic** [comment] 2022-01-12 16:04
I'm having the same issue with paperless-ng 1.5.0 and the latest app version.
Tried both with and without a trailing slash, neither work.

**Comment by qcasey** [comment] 2022-01-12 16:45
I'm having trouble reproducing this issue. For all those still affected, could you please post the result of:

```bash
curl -vvv https://paperless-demo.quinncasey.com/api/token/
```

Of course, replacing the URL with your instance. 

**Fix idea/notes**

Note the `< HTTP/2 405` response when hitting my paperless-ng 1.5.0 demo instance. The error dialog you're seeing could be a rewrite/routing issue, responding 200 when we try to detect the API for paperless-ng.

https://github.com/bauerj/paperless_app/blob/47dda078e2c2ef39468635d66850c02b637cb8ea/lib/api.dart#L246-L254

One way around this is doing the reverse: assuming paperless-ng and testing for the original paperless project. That might be disruptive though.

**Comment by amihaic** [comment] 2022-01-12 17:46
100% my bad. I'm using paperless-ng behind SWAG with Authelia. Once I removed the Authelia includes I could login with the app.

**Comment by qcasey** [comment] 2022-01-12 17:51
No worries, see #53 for paths to whitelist if necessary.

@siddharthdevilz I'm going to close this again, but if you or anyone else still has this issue let us know.

**Closed by qcasey** 2022-01-12 17:51 UTC
Labels: bug

**Comment by Bullnados** [comment] 2022-01-21 06:10
I have the same problem, my paperless is installed via docker on openmediavault NAS, NAS is not reachable via internet, just locally.

`wget -vvv https://192.123.456.5:8010/api/t
oken/
--2022-01-21 07:05:22--  https://192.123.456.5:8010/api/token/
Connecting to 192.168.178.5:8010... connected.
GnuTLS: The TLS connection was non-properly terminated.
Unable to establish SSL connection.`

**Comment by bauerj** [comment] 2022-01-21 07:16
Does it work in a browser? And are you sure this is not plain http://?

**Comment by Bullnados** [comment] 2022-01-21 12:07
🤦‍♂️ You are right http not https, in normal browser will be redirected.
Https is working
